name: 'Kitchen Dokken'
author: 'Jason Field'
description: 'Run Test Kitchen with Dokken easily'
inputs:
  suite:
    description: 'Which suite to run'
    required: true
  os:
    description: 'Operating System to run tests on'
    required: true
runs: 
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'tool'
  color: 'red'
